version: "3.8"

services:
  comfyui:
    image: aunymoons/comfyui-runpod:1.4
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - .env
    runtime: nvidia
    volumes:
      - ./data/comfyui/output:/comfyui/output
